server {
  listen 80;
  root /usr/share/nginx/html;
  index index.html;

  location = / {
    add_header Cache-Control "no-store";
    try_files /index.html =404;
  }

  location = /api/login {
    proxy_pass http://auth:8003/login;
  }

  location = /api/register {
    proxy_pass http://auth:8003/register;
  }

  location = /api/admin/products {
    proxy_pass http://products:8002/admin/products;
  }

  location /api/products {
    proxy_pass http://products:8002/products;
  }

  location = /api/stock {
    proxy_pass http://inventory:8001/stock;
  }

  location = /api/stock/events {
    proxy_pass http://inventory:8001/events;
    proxy_buffering off;
    proxy_cache off;
    proxy_read_timeout 1h;
  }

  location = /api/products/events {
    proxy_pass http://products:8002/events;
    proxy_buffering off;
    proxy_cache off;
    proxy_read_timeout 1h;
  }

  location = /api/order-history {
    proxy_pass http://orders:8000/orders;
  }

  location = /api/admin/orders {
    proxy_pass http://orders:8000/admin/orders;
  }

  location /api/admin/orders/ {
    proxy_pass http://orders:8000/admin/orders/;
  }

  location = /api/order-events {
    proxy_pass http://orders:8000/events;
    proxy_buffering off;
    proxy_cache off;
    proxy_read_timeout 1h;
  }

  location /api/admin/products/ {
    proxy_pass http://products:8002/admin/products/;
  }

  location /api/admin/stock {
    proxy_pass http://inventory:8001/stock/enable;
  }

  location = /api/admin/stock/restock {
    proxy_pass http://inventory:8001/stock/restock;
  }

  location /api/orders {
    proxy_pass http://orders:8000/orders;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
